---
- name: Setup Server for pre-requisits for Jenkins
  hosts: all
  become: yes
  tasks:
    - name: Install java
      yum:
        name: java-1.8.0
        state: present
    - name: Install Git
      yum:
        name: git
        state: present
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Services
      service:
        name: docker
        state: started
        enabled: yes


